name: PR actions
on:
  pull_request:
    branches:
      - v1.x
jobs:
  Cypress:
    uses: vtex/action-io-app-cypress/.github/workflows/cypress.yml@v1
    with:
      accounts: '["biggy"]'
      tests-repository: vtex/search-tests
      containers: 4
      parallel: true
    secrets:
      app-key: ${{ secrets.APP_KEY }}
      app-token: ${{ secrets.APP_TOKEN }}
      record-key: ${{ secrets.RECORD_KEY }}
